### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by kylebarron** [geopolars/geopolars#1]
Throwing around some ideas in a longer form than in the [polars issue](https://github.com/pola-rs/polars/issues/1830#issuecomment-1125251379).

## Premise

Geopandas has been a huge success for making vector geospatial data easy to use. It's the gold standard, but still has some limitations:

- Tied to Pandas. Pandas is not the most performant dataframe library; polars can be significanty faster.
- Tied to Python: Geopandas can't run where Python can't run. So for example a WASM build of geopandas would need the entire Python interpreter
- Tied to Numpy memory: This could change in the future, but for the time being, pandas is tied to numpy, which means that it requires a copy to/from Arrow memory, and historically hasn't had support for null values.
- Tied to GEOS. Data needs to be serialized to/from GEOS memory, which involves a copy and serialization to/from.

The ideal future:

- Store data in geoparquet with arrow-native geometry encoding, then load data into geoarrow in memory
- **or** memory map arrow data on disk directly
- With no copy, run geospatial operations

## How to extend Polars

Inheritance doesn't exist in Rust, at least not in the way it does in other languages like Python/JS, so we need to consider another way.

### External Traits

Probably the best approach here. It looks like it's possible to [define traits for external structs](https://eli.thegreenplace.net/2022/rust-extension-traits-greppability-and-ides/), and this is indeed how Serde works. This is probably the first place for exploration.

Pseudocode:
```rs
use polars::prelude::{DataFrame};

trait GeoDataFrame {
    fn area(&self) -> Series<f64>;
}

impl GeoDataFrame for DataFrame {
    fn area(&self) -> Series<f64> {
        // Connect to geo's area function
    }
}
```

### Wrapping `polars::DataFrame`

This doesn't seem very promising as a `GeoDataFrame` would be different from a `DataFrame`. Having to pipe polars methods through to a `GeoDataFrame` feels very against idiomatic Rust.

## Storing associated metadata

If we go with the external traits approach, then we need some way to store extra metadata about the dataframe. At least:

- CRS of the data
- Name of primary geometry column
- Geometry type
- How the column was stored

So... pretty much exactly what the geoarrow metadata defines. It would be great to align exactly with the geoarrow metadata. But there's still a question of how to actually store this. There is a [`schema` method](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html#method.schema) on the `DataFrame` struct, but it [doesn't look like it allows storing metadata](https://docs.rs/polars/latest/polars/chunked_array/object/struct.Schema.html).

This might be a good issue to raise in Polars.

## Geometry format

GeoArrow is the obvious contender for an in-memory format here. It would support zero-copy operations, which would allow parallelizing of row-wise geometry operations. I was able to see that a WKB-encoded column loads fine in the polars Python bindings, being exposed as a `List[u8]`. I haven't checked yet if a `List[List[FixedSizeList(2)]]` is already supported in Polars.

## Geospatial algorithms

The `geo` crate already has a bunch of great algorithms implemented in pure Rust. 

The awesome part here is [geozero](https://github.com/georust/geozero):

> GeoZero defines an API for reading geospatial data formats without an intermediate representation. It defines traits which can be implemented to read and convert to an arbitrary format or render geometries directly.

For WKB storage of geometries, it's already implemented. Meanwhile, we could add support for GeoArrow into geozero in the future, which would presumably be faster than WKB, especially if there's no intermediate representation.

I definitely still have questions about how geozero actually works though. Does it really mean that `geo`'s algorithms can run on geozero input with no transformation? So the input data doesn't get copied into `geo`'s structs?

**Comment by roger120981** [comment]
The idea of using GeoArrow as a standard format seems good to me, as you yourself implement in the exploration branch, you have a native reader in rust/polars, but there is something that raises my doubts, there is a high availability of datasets in other popular formats as geojson, kml, shp that opens the door to perhaps find a solution as Geopandas does, implement a generic read_file() method, which returns a geodataframe df and from this apply the algorithms present in Geo crate.
  Or something like that; I would open up the possibilities of use, I know it sounds a bit like geopandas, but it's just one possibility to explore.

**Comment by kylebarron** [comment]
You're referring to _file formats_, not _memory formats_. File formats can be parsed into a memory format on load.
