### ISSUE TITLE
Test with shapely v2

### ISSUE THREAD

**Issue by kylebarron** [geopolars/geopolars#149]

**Comment by mchalecki** [comment]
How would you like this integrated ? To represent arrow array as shapely in python ?

**Comment by kylebarron** [comment]
I don't think we can represent an arrow array as shapely directly. I was thinking more: check which apis have changed from v1 to v2, and soon-ish with an arrow-native encoding here, we should be able to use this [native shapely pr](https://github.com/shapely/shapely/pull/1559) to more efficiently move data between geoarrow and shapely

**Comment by kylebarron** [comment]
This is better implemented as of https://github.com/geopolars/geopolars/pull/187. See: https://github.com/geopolars/geopolars/blob/8cc532e72442eb6e396fa1d2076ecf9326efc738/py-geopolars/python/geopolars/internals/geoseries.py#L71-L129
